attempt 1 at lsp on arm

diff --git a/lsp/Dockerfile b/lsp/Dockerfile
--- a/lsp/Dockerfile
+++ b/lsp/Dockerfile
@@ -2,8 +2,24 @@ FROM nikolaik/python-nodejs:python3.11-nodejs19-slim
 
 RUN yarn global add diagnostic-languageserver
 RUN yarn global add pyright
-RUN wget https://golang.org/dl/go1.19.3.linux-amd64.tar.gz && tar -C /usr/local -xzf go1.19.3.linux-amd64.tar.gz
-ENV PATH="${PATH}:/usr/local/go/bin:/root/go/bin"
+RUN set -eux; \
+    arch="$(dpkg --print-architecture)"; arch="${arch##*-}"; \
+    url=; \
+    case "$arch" in \
+    'amd64') \
+    targz='go1.19.3.linux-amd64.tar.gz'; \
+    ;; \
+    'arm64') \
+    targz='go1.19.3.linux-arm64.tar.gz'; \
+    ;; \
+    'armhf') \
+    targz='go1.19.3.linux-armv6l.tar.gz'; \
+    ;; \
+    *) echo >&2 "error: unsupported architecture '$arch' (likely packaging update needed)"; exit 1 ;; \
+    esac; \
+    wget "https://golang.org/dl/$targz" -nv && tar -C /usr/local -xzf "$targz" && rm "$targz";
+
+ENV PATH="${PATH}:/usr/local/go/bin"
 ENV GO_PATH=/usr/local/go/bin/go
 ENV GOROOT=/usr/local/go
 RUN /usr/local/go/bin/go install -v golang.org/x/tools/gopls@latest
